<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var \Kadoco\Snapchat\ViewModel\SnapchatSuccessDataProvider $snapchatSuccess */
$snapchatSuccess = $block->getData('SnapchatSuccessDataProvider');
$purchaseData = $snapchatSuccess->getPurchaseData();
$email = $snapchatSuccess->getUserEmail();
/** @var \Kadoco\Snapchat\ViewModel\SnapchatDataProvider $snapchat */
$snapchat = $block->getData('SnapchatDataProvider');
?>
<!-- Snap Pixel Code -->
<script type='text/javascript'>
    (function(e,t,n){
            if(e.snaptr)
                return;
            var a=e.snaptr=function() {
                a.handleRequest?a.handleRequest.apply(a,arguments):a.queue.push(arguments)
            };
            a.queue=[];
            var s='script';
            r=t.createElement(s);
            r.async=!0;
            r.src=n;
            var u=t.getElementsByTagName(s)[0];
            u.parentNode.insertBefore(r,u);
        }
    ) (window,document, 'https://sc-static.net/scevent.min.js');
    <?php if ($email): ?>
        snaptr('init', '<?=$snapchat->getPixelId()?>', <?=json_encode(['user_email' => $email])?>);
    <?php else: ?>
        snaptr('init', '<?=$snapchat->getPixelId()?>');
    <?php endif; ?>

    snaptr('track', 'PAGE_VIEW');
    <?php if ($purchaseData): ?>
        snaptr('track', 'PURCHASE', <?=$purchaseData?>);
    <?php endif; ?>
</script>
